apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  labels:
    app: phpldapadmin
    heritage: Kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
      release: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
        release: phpldapadmin
    spec:
      containers:
        - name: phpldapadmin
          image: "osixia/phpldapadmin:0.9.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: phpldapadmin
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
