apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: acid-test2
  namespace: default
spec:
  allowedSourceRanges: null
  numberOfInstances: 1
  postgresql:
    version: '14'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  volume:
    size: "10Gi"
