apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kube-oidc-proxy
  name: kube-oidc-proxy
  namespace: kube-oidc-proxy
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  type: ClusterIP
  selector:
    app: kube-oidc-proxy
