apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: kube-oidc-proxy
  cluster: docker-desktop
namespace: kube-oidc-proxy
resources:
  - clusterrolebinding.yaml
  - ingress.yaml
