replicaCount: 1

logLevel: debug

env:
  LDAP_LOG_LEVEL: "256"
  LDAP_ORGANISATION: "Nephtek Demo"
  LDAP_DOMAIN: "nephtek.com"
  LDAP_READONLY_USER: "true"
  LDAP_READONLY_USER_USERNAME: "readonly"
  LDAP_READONLY_USER_PASSWORD: "password"
  LDAP_RFC2307BIS_SCHEMA: "false"
  LDAP_BACKEND: "hdb"
  LDAP_TLS: "true"
  LDAP_TLS_CRT_FILENAME: "tls.crt"
  LDAP_TLS_KEY_FILENAME: "tls.key"
  LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
  LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
  LDAP_TLS_ENFORCE: "false"
  CONTAINER_LOG_LEVEL: "4"
  LDAP_TLS_REQCERT: "never"
  KEEP_EXISTING_CONFIG: "false"
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
  LDAP_SSL_HELPER_PREFIX: "ldap"
  LDAP_TLS_VERIFY_CLIENT: "never"
  LDAP_TLS_PROTOCOL_MIN: "3.0"
  LDAP_TLS_CIPHER_SUITE: "NORMAL"

adminPassword: "admin"
configPassword: "config"

customLdifFiles:
  initial-ous.ldif: |-
    dn: ou=People,dc=nephtek,dc=com
    objectClass: organizationalUnit
    ou: People

    dn: ou=Group,dc=nephtek,dc=com
    objectClass: organizationalUnit
    ou: Group

ltb-passwd:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: nephtek-com-issuer
    path: /
    pathType: Prefix
    hosts:
      - "ssl-ldap2.k8s.nephtek.com"
    tls:
      - hosts:
          - "ssl-ldap2.k8s.nephtek.com"
        secretName: ssl-ldap2-k8s-crt
  ldap:
    server: ldap://openldap-openldap-stack-ha
    searchBase: dc=nephtek,dc=com
    # existingSecret: openldaptest
    bindDN: cn=admin,dc=nephtek,dc=com
    bindPWKey: LDAP_ADMIN_PASSWORD

phpldapadmin:
  ingress:
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: nephtek-com-issuer
    hosts:
      - "phpldapadmin.k8s.nephtek.com"
    tls:
      - hosts:
          - "phpldapadmin.k8s.nephtek.com"
        secretName: phpldapadmin-k8s-crt
  env:
    PHPLDAPADMIN_LDAP_HOSTS: openldap-openldap-stack-ha
    PYTHON2BASH:
      "[{'openldap.openldap':
         [{'server': [
           {'tls': False},
           {'port':636}
         ]},
           {'login':
             [{'bind_id': 'cn=admin,dc=nephtek,dc=com'}]
           }]
       }]"
