alertmanager:
  ingress:
    enabled: true

grafana:
  ingress:
    enabled: true
  additionalDataSources:
    - name: Loki
      url: http://loki.gateway.svc.cluster.local
      type: loki

prometheus:
  ingress:
    enabled: true
