apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak-sso
  namespace: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  #extensions:
  #  - https://keycloak-themes.k8s.nephtek.com/theme.jar
  externalAccess:
    enabled: False
    host: keycloak.k8s.nephtek.com
  podDisruptionBudget:
    enabled: True
  # User needs to provision the external database
  externalDatabase:
    enabled: True
