apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: grafana-k8s-nephtek-com
  labels:
    app: keycloak
spec:
  realmSelector:
    matchLabels:
      app: keycloak
  roles:
    - name: admin
    - name: editor
    - name: viewer
  client:
    clientId: grafana.k8s.nephtek.com
    secret: VxG2Tfpbfurn7c5VQ44rnJx9DitOcie9
    rootUrl: "${authBaseUrl}"
    adminUrl: ""
    baseUrl: "/login/generic_oauth"
    surrogateAuthRequired: false
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    enabled: true
    redirectUris:
      - "https://grafana.k8s.nephtek.com/login/generic_oauth"
    webOrigins: [""]
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    frontchannelLogout: false
    attributes:
      saml.multivalued.roles: "false"
      saml.force.post.binding: "false"
      oauth2.device.authorization.grant.enabled: "false"
      backchannel.logout.revoke.offline.tokens: "false"
      saml.server.signature.keyinfo.ext: "false"
      use.refresh.tokens: "true"
      oidc.ciba.grant.enabled: "false"
      backchannel.logout.session.required: "true"
      client_credentials.use_refresh_token: "false"
      saml.client.signature: "false"
      require.pushed.authorization.requests: "false"
      saml.assertion.signature: "false"
      id.token.as.detached.signature: "false"
      saml.encrypt: "false"
      saml.server.signature: "false"
      exclude.session.state.from.auth.response: "false"
      saml.artifact.binding: "false"
      saml_force_name_id_format: "false"
      tls.client.certificate.bound.access.tokens: "false"
      acr.loa.map: "{}"
      saml.authnstatement: "false"
      display.on.consent.screen: "false"
      token.response.type.bearer.lower-case: "false"
      saml.onetimeuse.condition: "false"
    authenticationFlowBindingOverrides: {}
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    defaultClientScopes:
      - "web-origins"
      - "roles"
      - "profile"
      - "email"
    optionalClientScopes:
      - "address"
      - "phone"
      - "offline_access"
      - "microprofile-jwt"
    protocolMappers:
      - id: "bf06c911-b900-423b-a7f5-0487b41d6b22"
        name: "Roles"
        protocol: "openid-connect"
        protocolMapper: "oidc-usermodel-client-role-mapper"
        consentRequired: false
        config:
          multivalued: "true"
          userinfo.token.claim: "true"
          id.token.claim: "true"
          access.token.claim: "true"
          claim.name: "roles"
          jsonType.label: "String"
          usermodel.clientRoleMapping.clientId: "grafana.k8s.nephtek.com"
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: kube-oidc-proxy
  labels:
    app: keycloak
spec:
  realmSelector:
    matchLabels:
      app: keycloak
  client:
    clientId: kube-oidc-proxy
    secret: n2vlpXqrNb2caUStw9PQRIJHczHjXamE
    surrogateAuthRequired: false
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    enabled: true
    redirectUris:
      - "http://localhost:18000"
      - "http://localhost:8000"
    webOrigins: [""]
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    frontchannelLogout: false
    attributes:
      saml.multivalued.roles: "false"
      saml.force.post.binding: "false"
      oauth2.device.authorization.grant.enabled: "false"
      backchannel.logout.revoke.offline.tokens: "false"
      saml.server.signature.keyinfo.ext: "false"
      use.refresh.tokens: "true"
      oidc.ciba.grant.enabled: "false"
      backchannel.logout.session.required: "true"
      client_credentials.use_refresh_token: "false"
      saml.client.signature: "false"
      require.pushed.authorization.requests: "false"
      saml.assertion.signature: "false"
      id.token.as.detached.signature: "false"
      saml.encrypt: "false"
      saml.server.signature: "false"
      exclude.session.state.from.auth.response: "false"
      saml.artifact.binding: "false"
      saml_force_name_id_format: "false"
      tls.client.certificate.bound.access.tokens: "false"
      acr.loa.map: "{}"
      saml.authnstatement: "false"
      display.on.consent.screen: "false"
      token.response.type.bearer.lower-case: "false"
      saml.onetimeuse.condition: "false"
    authenticationFlowBindingOverrides: {}
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    defaultClientScopes:
      - "web-origins"
      - "roles"
      - "profile"
      - "groups"
      - "email"
    optionalClientScopes:
      - "address"
      - "phone"
      - "offline_access"
      - "microprofile-jwt"
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: oauth2-proxy
  labels:
    app: keycloak
spec:
  realmSelector:
    matchLabels:
      app: keycloak
  client:
    clientId: oauth2-proxy
    secret: 8g9HPckTsPy947W7X7qx4Be5pmOPL2ha
    surrogateAuthRequired: false
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    enabled: true
    redirectUris:
      - "https://oauth2.k8s.nephtek.com/oauth2/callback"
      - "https://prometheus.k8s.nephtek.com/oauth2/callback"
      - "https://alertmanager.k8s.nephtek.com/oauth2/callback"
    webOrigins: [""]
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    frontchannelLogout: false
    attributes:
      saml.multivalued.roles: "false"
      saml.force.post.binding: "false"
      oauth2.device.authorization.grant.enabled: "false"
      backchannel.logout.revoke.offline.tokens: "false"
      saml.server.signature.keyinfo.ext: "false"
      use.refresh.tokens: "true"
      oidc.ciba.grant.enabled: "false"
      backchannel.logout.session.required: "true"
      client_credentials.use_refresh_token: "false"
      saml.client.signature: "false"
      require.pushed.authorization.requests: "false"
      saml.assertion.signature: "false"
      id.token.as.detached.signature: "false"
      saml.encrypt: "false"
      saml.server.signature: "false"
      exclude.session.state.from.auth.response: "false"
      saml.artifact.binding: "false"
      saml_force_name_id_format: "false"
      tls.client.certificate.bound.access.tokens: "false"
      acr.loa.map: "{}"
      saml.authnstatement: "false"
      display.on.consent.screen: "false"
      token.response.type.bearer.lower-case: "false"
      saml.onetimeuse.condition: "false"
    authenticationFlowBindingOverrides: {}
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    defaultClientScopes:
      - "web-origins"
      - "roles"
      - "profile"
      - "groups"
      - "email"
    optionalClientScopes:
      - "address"
      - "phone"
      - "offline_access"
      - "microprofile-jwt"
---
