apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-k8s-nephtek-com
  namespace: keycloak
spec:
  dnsNames:
  - keycloak.k8s.nephtek.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: nephtek-com-issuer
  secretName: sso-x509-https-secret
