apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: kube-oidc-proxy
  cluster: rancher-desktop
namespace: kube-oidc-proxy
resources:
  - ../../base/
  - secrets
  - ingress.yaml
