ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: nephtek-com-issuer
  hosts:
  - host: postgres-ui.nephtek.com
    paths: [""]
  tls:
    - hosts:
        - postgres-ui.nephtek.com
      secretName: postgres-ui-nephtek-com-tls
