apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-nephtek-com
spec:
  secretName: k8s-nephtek-com-tls
  dnsNames:
  - "*.k8s.nephtek.com"
  - "k8s.nephtek.com"
  issuerRef:
    name: nephtek-com-issuer
    kind: ClusterIssuer
    group: cert-manager.io
