apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nephtek-com-issuer
spec:
  acme:
    email: dan@nephtek.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: k8s-nephtek-com-key
    solvers:
    - dns01:
        cloudflare:
          email: dan@frissoncomputing.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - k8s.nephtek.com
